name: Deploy to Github Pages

on:
  push:
    branches:
      - master

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH key
      uses: shivammathur/setup-ssh@v1
      with:
        ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

    - name: Deploy to Github Pages
      run: |
        cd public
        git config user.name "Github Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Auto-deployment by Github Actions"
        git push -f origin master
      env:
        GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no